Fix spot instance launch readiness
hashicorp/packer-plugin-amazon pull request #308
Opened 2023-01-14 00:37 UTC by sparrc

When launching ec2 source instances, we have code which waits for the instance to become ready, but previously this codepath was not being applied to spot instances.

This change factors that code out into a common function, and then calls that common function in both the 'regular' and 'spot' instance launches.

This fixes issues where packer tries to connect to a spot instance before it is running and ready, which means it won't have a public ip address ready yet, and so packer times out on SSH access.

fixes #40

2023-01-14 00:37 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer-plugin-amazon?pullRequest=308)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer-plugin-amazon?pullRequest=308)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer-plugin-amazon?pullRequest=308).</sub>

2023-01-14 00:43 UTC, yinyic approved these changes

2023-01-16 16:44 UTC, lbajolet-hashicorp requested changes
Hi @sparrc,

Thanks for the fix, this looks good to me overall, however I notice that the type change in the `step_run_spot_instance.go` file for the `ec2conn` will break tests.

We don't have any test for the `step_run_source_instance`, but we do for the `step_run_spot_instance`, and it creates the connection using a EC2Mock.
Because of this, the type cast fails, and the test crashes.

In order to fix this, we should accept any `ec2iface.EC2API` for the `WaitUntilInstanceRunning` function. Fortunately it is something we define, so this should be fixable.

In its current state then we cannot merge this, but once this is fixed, I'll be glad to give this PR another review, and eventually merge it.

Do you need any assistance fixing this problem? If so do let me know, I'll do a pass on the code and fix the typing problem.

Thanks again for this fix, hopefully we can merge it soon!

2023-01-17 17:22 UTC, sparrc commented
Thanks for the review, I will take a look at that, I think I should be able to fix it

2023-01-17 19:01 UTC, sparrc commented
Updated to PR to use `ec2iface.EC2API` down into `WaitUntilInstanceRunning`, thanks again for the review @lbajolet-hashicorp !

2023-01-17 19:15 UTC, sparrc commented
Now it seems like the mocks are panicking when `ec2conn.WaitUntilInstanceRunningWithContext` is called. Not exactly sure why that is though? Do the mocks need to be regenerated?

2023-01-17 21:09 UTC, lbajolet-hashicorp approved these changes
Hi @sparrc,

Thanks for following up with this, the code in its current state looks good to me, and tests are passing, I'll merge this right away.

2023-01-17 21:10 UTC, merged