[draft] add circle config for branch tests
hashicorp/packer-plugin-amazon pull request #84
Opened 2021-05-26 21:06 UTC by SwampDragons

need to be able to run branch tests on this repo

2021-05-31 09:46 UTC, sylviamoss requested changes
This looks good! 
I'm requesting changes because of the persistent part, I think it has to be adapted for plugins. Also, I would add this to our packer-repositories to add it to all of the plugins 🤔  what do you think?

2021-05-31 09:46 UTC, sylviamoss commented on .circleci/config.yml
> +            - ./pkg/
This is very packer-specific. Plugins don't have the GitCommit commit constant, we will need to implement that.  I also think the zip should have the plugin name.

2021-05-31 09:49 UTC, sylviamoss commented
Another option is to update the pull request action to also run for branches with something like 
```
on: [push, pull_request]
```

2021-06-01 13:47 UTC, nywilken commented
@sylviamoss these are some great suggestions. We merged a PR last week into packer-repositories to push this change to all repos. Would you mind making your suggested changes to the packer-repositories since you have these top of mind so that we can push the final config to all repos at once. I will approve, push, and apply. 

I'm closing this PR as it has been superseded by the packer-repositories change.

2021-06-01 13:47 UTC, closed without merging